export type Diet = "all" | "meat_only" | "vegetarian" | "vegan";

export type Allergen =
  | "gluten"
  | "wheat"
  | "rye"
  | "barley"
  | "oats"
  | "spelt"
  | "crustacean"
  | "egg"
  | "fish"
  | "peanut"
  | "soy"
  | "milk"
  | "lactose"
  | "nut"
  | "celery"
  | "mustard"
  | "sesame"
  | "sulfite"
  | "lupin"
  | "mollusc"
  | "alcohol"
  | "caffeine"
  | "quinine"
  | "preservative"
  | "nitrite"
  | "antioxidant"
  | "colorant"
  | "phosphate"
  | "sweetener"
  | "flavor_enhancer"
  | "gelatin"
  | "yeast"
  | "phenylalanine"
  | "laxative";
