name: Backend CI

on:
  push:
    branches:
      - main
      - development
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    branches:
      - main
      - development
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4