name: Frontend CI

on:
  push:
    branches:
      - main
      - development
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yml"
  pull_request:
    branches:
      - main
      - development
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yml"

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4